import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/core/server/prisma";
import { CmsPageShell } from "@/modules/cms/components/CmsPageShell";

export default async function CmsModulePreviewPage({ params }: { params: Promise<{ moduleId: string }> }) {
  const courseModule = await prisma.courseModule.findUnique({ where: { id: (await params).moduleId }, include: { course: { select: { id: true, title: true, level: { select: { code: true } } } }, unlockAfterModule: { select: { title: true, order: true } }, lessons: { orderBy: { order: "asc" }, include: { _count: { select: { blocks: true } } } } } });
  if (!courseModule) notFound();
  return <CmsPageShell eyebrow="Learner preview" title={courseModule.title} description={courseModule.description ?? "No module description."} actions={<Link href={`/cms/modules/${courseModule.id}`} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold hover:bg-white">Back to editor</Link>}><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-sm font-semibold text-blue-700">{courseModule.course.level.code} · {courseModule.course.title}</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full bg-slate-100 px-3 py-1">{courseModule.isRequired ? "Required" : "Optional"}</span>{courseModule.requiresSequentialCompletion ? <span className="rounded-full bg-amber-50 px-3 py-1 text-amber-800">Previous module must be complete</span> : null}{courseModule.unlockAfterModule ? <span className="rounded-full bg-amber-50 px-3 py-1 text-amber-800">After {courseModule.unlockAfterModule.order}. {courseModule.unlockAfterModule.title} · {courseModule.requiredCompletionPercent}%</span> : null}</div><h2 className="mt-6 text-2xl font-bold text-slate-950">Lesson outline</h2><ol className="mt-4 space-y-3">{courseModule.lessons.map((lesson) => <li key={lesson.id} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold text-slate-950">{lesson.order}. {lesson.title}</p><p className="mt-1 text-sm text-slate-600">{lesson.description ?? "No lesson description."} · {lesson.estimatedDuration || "—"} min · {lesson._count.blocks} blocks</p></li>)}</ol></section></CmsPageShell>;
}
