"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Item = { id: string; type: string; category: string; title: string; message: string; actionUrl: string | null; actionLabel: string | null; readAt: string | null; createdAt: string; status: string };
const categories = ["ALL", "ACCOUNT", "SECURITY", "LEARNING", "VOCABULARY", "MOTIVATION", "BILLING", "SUPPORT", "SYSTEM"];

export function NotificationCenter() {
  const [items, setItems] = useState<Item[]>([]); const [category, setCategory] = useState("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/notifications?limit=30${category === "ALL" ? "" : `&category=${category}`}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load notifications."); setItems(data.notifications || []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load notifications."); } finally { setLoading(false); } }, [category]);
  useEffect(() => { void load(); }, [load]);
  async function update(id: string, action: "read" | "archive") { const response = await fetch(`/api/notifications/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); if (response.ok) void load(); }
  async function readAll() { const response = await fetch("/api/notifications/read-all", { method: "POST" }); if (response.ok) void load(); }
  return <section className="mt-8"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-2">{categories.map((value) => <button key={value} type="button" onClick={() => setCategory(value)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${category === value ? "bg-blue-700 text-white" : "border border-slate-300 bg-white text-slate-700"}`}>{value}</button>)}</div><button type="button" onClick={() => void readAll()} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold hover:bg-slate-50">Mark all as read</button></div>{error ? <p role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-700">{error}</p> : null}<div className="mt-5 space-y-3">{loading ? <p className="text-slate-600">Loading notifications…</p> : items.length ? items.map((item) => <article key={item.id} className={`rounded-xl border p-5 ${item.readAt ? "border-slate-200 bg-white" : "border-blue-200 bg-blue-50"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">{item.category}</p><h2 className="mt-1 font-bold text-slate-900">{item.title}</h2><p className="mt-2 text-slate-700">{item.message}</p><p className="mt-2 text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</p></div><div className="flex gap-2">{item.actionUrl ? <Link href={item.actionUrl} onClick={() => void update(item.id, "read")} className="rounded-lg bg-blue-700 px-3 py-2 text-sm font-semibold text-white">{item.actionLabel || "Open"}</Link> : null}{!item.readAt ? <button type="button" onClick={() => void update(item.id, "read")} className="rounded-lg border px-3 py-2 text-sm">Read</button> : null}<button type="button" aria-label={`Archive ${item.title}`} onClick={() => void update(item.id, "archive")} className="rounded-lg border px-3 py-2 text-sm">Archive</button></div></div></article>) : <p className="rounded-xl border border-dashed p-6 text-slate-600">No notifications in this category.</p>}</div></section>;
}
