"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Category = { id: string; title: string; description: string | null };
export function SupportTicketForm() {
  const router = useRouter(); const [categories, setCategories] = useState<Category[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/support/categories").then((response) => response.json()).then((data) => setCategories(data.categories || [])).catch(() => undefined); }, []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/support/tickets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ categoryId: form.get("categoryId") || undefined, subject: form.get("subject"), description: form.get("description"), priority: form.get("priority") }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error || "Unable to create support ticket."); return; } router.push(`/profile/support/${data.ticket.id}`); }
  return <form onSubmit={(event) => void submit(event)} className="mt-8 space-y-5 rounded-2xl border bg-white p-6"><label className="block font-medium">Category<select name="categoryId" className="mt-2 w-full rounded-lg border p-3"><option value="">General question</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.title}</option>)}</select></label><label className="block font-medium">Priority<select name="priority" defaultValue="NORMAL" className="mt-2 w-full rounded-lg border p-3"><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></label><label className="block font-medium">Subject<input required name="subject" maxLength={180} className="mt-2 w-full rounded-lg border p-3" placeholder="How can we help?" /></label><label className="block font-medium">Message<textarea required name="description" minLength={5} maxLength={8000} rows={7} className="mt-2 w-full rounded-lg border p-3" placeholder="Please describe the issue without passwords, card details, or other secrets." /></label>{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}<button disabled={loading} className="rounded-lg bg-blue-700 px-5 py-3 font-semibold text-white disabled:opacity-60">{loading ? "Sending…" : "Create support ticket"}</button><p className="text-xs text-slate-500">Attachments require the platform storage provider and are not accepted by this form yet.</p></form>;
}
