ALTER TYPE "LessonType" ADD VALUE IF NOT EXISTS 'THEORY';
ALTER TYPE "LessonType" ADD VALUE IF NOT EXISTS 'PRACTICE';
ALTER TYPE "LessonType" ADD VALUE IF NOT EXISTS 'TEST';
ALTER TYPE "LessonType" ADD VALUE IF NOT EXISTS 'PROJECT';
ALTER TYPE "LessonType" ADD VALUE IF NOT EXISTS 'MIXED';
