"use client";

import { FormEvent, useEffect, useState } from "react";

type FoundWord = { id: string; lemma: string; meanings: Array<{ translation: string | null; definition: string }> };

export function AddCustomWordForm() {
  const [term, setTerm] = useState("");
  const [translation, setTranslation] = useState("");
  const [partOfSpeech, setPartOfSpeech] = useState("");
  const [example, setExample] = useState("");
  const [note, setNote] = useState("");
  const [matches, setMatches] = useState<FoundWord[]>([]);
  const [status, setStatus] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  useEffect(() => { if (term.trim().length < 2) { setMatches([]); return; } const controller = new AbortController(); const timer = window.setTimeout(() => { void fetch(`/api/vocabulary/search?q=${encodeURIComponent(term)}`, { signal: controller.signal }).then((response) => response.ok ? response.json() : null).then((payload: { data?: FoundWord[] } | null) => setMatches(payload?.data ?? [])).catch(() => undefined); }, 250); return () => { controller.abort(); window.clearTimeout(timer); }; }, [term]);
  async function add(body: object) { setSaving(true); setStatus(null); try { const response = await fetch("/api/profile/vocabulary", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Unable to add word"); setTerm(""); setTranslation(""); setPartOfSpeech(""); setExample(""); setNote(""); setMatches([]); setStatus("Word added. First review is scheduled for today."); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to add word"); } finally { setSaving(false); } }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await add({ term, translation, partOfSpeech: partOfSpeech || undefined, example: example || undefined, note: note || undefined }); }
  return <form onSubmit={(event) => void submit(event)} className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-900">Add a word</h2><p className="mt-1 text-sm text-slate-600">We search the central dictionary first. Your own words stay private.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><label><span className="text-sm font-medium">Word or phrase</span><input required value={term} onChange={(event) => setTerm(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label><span className="text-sm font-medium">Translation</span><input required value={translation} onChange={(event) => setTranslation(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label><span className="text-sm font-medium">Part of speech</span><select value={partOfSpeech} onChange={(event) => setPartOfSpeech(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">Not specified</option>{["NOUN", "VERB", "ADJECTIVE", "ADVERB", "PHRASE", "PHRASAL_VERB", "IDIOM", "OTHER"].map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="text-sm font-medium">Example</span><input value={example} onChange={(event) => setExample(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="md:col-span-2"><span className="text-sm font-medium">Comment</span><textarea value={note} onChange={(event) => setNote(event.target.value)} className="mt-1 min-h-20 w-full rounded-lg border border-slate-300 px-3 py-2" /></label></div>{matches.length ? <div className="mt-4 rounded-xl bg-blue-50 p-4"><p className="text-sm font-semibold text-blue-950">Found in the central dictionary</p><div className="mt-2 flex flex-wrap gap-2">{matches.map((word) => <button key={word.id} type="button" disabled={saving} onClick={() => void add({ wordId: word.id })} className="rounded-lg border border-blue-200 bg-white px-3 py-2 text-left text-sm hover:bg-blue-100"><span className="font-semibold">{word.lemma}</span><span className="ml-2 text-slate-600">{word.meanings[0]?.translation ?? word.meanings[0]?.definition}</span></button>)}</div></div> : null}<button disabled={saving} className="mt-4 rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white hover:bg-blue-800 disabled:opacity-60">{saving ? "Adding…" : "Add my word"}</button>{status ? <p className="mt-3 text-sm text-slate-700" role="status">{status}</p> : null}</form>;
}
