"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

async function post(url: string, body: object) { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Request failed"); }
function useSubmit() { const router = useRouter(); const [message, setMessage] = useState<string | null>(null); async function submit(url: string, event: FormEvent<HTMLFormElement>, body: object, success: string) { event.preventDefault(); try { await post(url, body); setMessage(success); event.currentTarget.reset(); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save."); } } return { message, submit }; }

export function PlanForm() { const { message, submit } = useSubmit(); return <form onSubmit={(event) => { const form = new FormData(event.currentTarget); void submit("/api/admin/billing/plans", event, { code: form.get("code"), slug: form.get("slug"), title: form.get("title"), description: form.get("description"), type: "SUBSCRIPTION", billingPeriod: form.get("billingPeriod"), priceAmount: Number(form.get("priceAmount")), currency: form.get("currency"), trialDays: Number(form.get("trialDays")), isPublic: true, isFeatured: form.get("isFeatured") === "on" }, "Plan created."); }} className="mt-5 grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><h2 className="text-xl font-bold md:col-span-3">Create plan</h2><label>Code<select name="code" className="mt-1 w-full rounded border p-2">{["FREE", "BASIC", "PREMIUM", "PRO", "CORPORATE"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Slug<input required name="slug" className="mt-1 w-full rounded border p-2" /></label><label>Title<input required name="title" className="mt-1 w-full rounded border p-2" /></label><label className="md:col-span-3">Description<input required name="description" className="mt-1 w-full rounded border p-2" /></label><label>Period<select name="billingPeriod" className="mt-1 w-full rounded border p-2"><option>MONTH</option><option>YEAR</option><option>NONE</option></select></label><label>Price, minor units<input name="priceAmount" type="number" min="0" defaultValue="0" className="mt-1 w-full rounded border p-2" /></label><label>Currency<select name="currency" className="mt-1 w-full rounded border p-2"><option>USD</option><option>UAH</option><option>EUR</option></select></label><label>Trial days<input name="trialDays" type="number" min="0" defaultValue="0" className="mt-1 w-full rounded border p-2" /></label><label className="flex items-center gap-2"><input name="isFeatured" type="checkbox" /> Featured</label><div className="md:col-span-3"><button className="rounded bg-blue-700 px-4 py-2 font-semibold text-white">Create plan</button>{message ? <p role="status" className="mt-2 text-sm">{message}</p> : null}</div></form>; }

export function ProductForm() { const { message, submit } = useSubmit(); return <form onSubmit={(event) => { const form = new FormData(event.currentTarget); void submit("/api/admin/billing/products", event, { code: String(form.get("code")).toUpperCase(), slug: form.get("slug"), title: form.get("title"), description: form.get("description") || undefined, type: form.get("type"), courseId: form.get("courseId") || null, moduleId: form.get("moduleId") || null, planId: form.get("planId") || null, isPublic: true }, "Product created."); }} className="mt-5 grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><h2 className="text-xl font-bold md:col-span-3">Create product</h2><label>Code<input required name="code" className="mt-1 w-full rounded border p-2" placeholder="COURSE_ADVANCED" /></label><label>Slug<input required name="slug" className="mt-1 w-full rounded border p-2" /></label><label>Title<input required name="title" className="mt-1 w-full rounded border p-2" /></label><label>Type<select name="type" className="mt-1 w-full rounded border p-2">{["COURSE", "COURSE_BUNDLE", "MODULE", "LESSON_PACK", "SUBSCRIPTION_PLAN"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Course ID (optional)<input name="courseId" className="mt-1 w-full rounded border p-2" /></label><label>Module ID (optional)<input name="moduleId" className="mt-1 w-full rounded border p-2" /></label><label>Plan ID (subscription only)<input name="planId" className="mt-1 w-full rounded border p-2" /></label><label className="md:col-span-2">Description<input name="description" className="mt-1 w-full rounded border p-2" /></label><div className="md:col-span-3"><button className="rounded bg-blue-700 px-4 py-2 font-semibold text-white">Create product</button>{message ? <p role="status" className="mt-2 text-sm">{message}</p> : null}</div></form>; }

export function PriceForm() { const { message, submit } = useSubmit(); return <form onSubmit={(event) => { const form = new FormData(event.currentTarget); void submit("/api/admin/billing/prices", event, { productId: form.get("productId"), provider: form.get("provider"), currency: form.get("currency"), amount: Number(form.get("amount")), billingPeriod: form.get("billingPeriod"), providerPriceId: form.get("providerPriceId") || null }, "Price created."); }} className="mt-5 grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><h2 className="text-xl font-bold md:col-span-3">Add product price</h2><label>Product ID<input required name="productId" className="mt-1 w-full rounded border p-2" /></label><label>Provider<select name="provider" className="mt-1 w-full rounded border p-2"><option>STRIPE</option><option>LIQPAY</option></select></label><label>Currency<select name="currency" className="mt-1 w-full rounded border p-2"><option>USD</option><option>UAH</option><option>EUR</option></select></label><label>Amount, minor units<input required name="amount" type="number" min="1" className="mt-1 w-full rounded border p-2" /></label><label>Period<select name="billingPeriod" className="mt-1 w-full rounded border p-2"><option>NONE</option><option>MONTH</option><option>YEAR</option></select></label><label>Provider price ID<input name="providerPriceId" className="mt-1 w-full rounded border p-2" /></label><div className="md:col-span-3"><button className="rounded bg-blue-700 px-4 py-2 font-semibold text-white">Add price</button>{message ? <p role="status" className="mt-2 text-sm">{message}</p> : null}</div></form>; }
