import Link from "next/link";
import { notFound } from "next/navigation";
import { VocabularyWordDetailsManager } from "@/modules/vocabulary/components/VocabularyWordDetailsManager";
import { getVocabularyWordForAdmin } from "@/modules/vocabulary/services/vocabulary.service";

export default async function VocabularyWordPage({ params }: { params: Promise<{ wordId: string }> }) {
  const word = await getVocabularyWordForAdmin((await params).wordId);
  if (!word) notFound();
  return <div><Link href="/admin/vocabulary" className="text-sm font-semibold text-blue-700 hover:underline">← Vocabulary CMS</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">{word.lemma}</h1><p className="mt-2 text-slate-600">{word.partOfSpeech ?? "No part of speech"} · {word.cefrLevel ?? "No CEFR"} · {word.isActive ? "Active" : "Inactive"}</p></div><p className="text-sm text-slate-500">{word._count.lessonVocabulary} lesson links · {word._count.userWords} learner entries</p></div><section className="mt-7 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Meanings</h2><ul className="mt-3 space-y-3">{word.meanings.map((meaning) => <li key={meaning.id}><p className="font-semibold">{meaning.translation ?? meaning.definition}</p><p className="text-sm text-slate-600">{meaning.definition}</p></li>)}</ul></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Examples and collocations</h2><ul className="mt-3 space-y-3 text-sm">{word.examples.map((example) => <li key={example.id}>{example.sentence}{example.translation ? ` — ${example.translation}` : ""}</li>)}{word.collocations.map((collocation) => <li key={collocation.id}><span className="font-semibold">{collocation.value}</span>{collocation.translation ? ` — ${collocation.translation}` : ""}</li>)}</ul></article></section><VocabularyWordDetailsManager wordId={word.id} isActive={word.isActive} initial={{ lemma: word.lemma, partOfSpeech: word.partOfSpeech, cefrLevel: word.cefrLevel, britishTranscription: word.britishTranscription, americanTranscription: word.americanTranscription, britishAudioUrl: word.britishAudioUrl, americanAudioUrl: word.americanAudioUrl }} /></div>;
}
