"use client";

import { FormEvent, useState } from "react";

export function GroupMembersPanel({ groupId, initialMembers }: { groupId: string; initialMembers: { id: string; name: string | null; email: string; status: string }[] }) {
  const [members, setMembers] = useState(initialMembers); const [email, setEmail] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const add = async (event: FormEvent) => { event.preventDefault(); setError(""); setNotice(""); const r = await fetch(`/api/teacher/groups/${groupId}/students`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const p = await r.json().catch(() => null); if (!r.ok) { setError(p?.error ?? "Unable to add learner."); return; } setMembers((prev) => prev.some((item) => item.id === p.data.id) ? prev : [...prev, { id: p.data.id, name: email, email, status: "ACTIVE" }]); setEmail(""); setNotice("Learner added to the group."); };
  const invite = async () => { setError(""); setNotice(""); const r = await fetch(`/api/teacher/groups/${groupId}/invitations`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const p = await r.json().catch(() => null); if (!r.ok) { setError(p?.error ?? "Unable to create invitation."); return; } setNotice(`Invitation link created: ${window.location.origin}${p.data.acceptPath}`); setEmail(""); };
  return <article className="rounded-xl border bg-white p-5"><h3 className="font-bold">Learners</h3><form onSubmit={add} className="mt-3 flex flex-wrap gap-2"><input value={email} onChange={(e) => setEmail(e.target.value)} required type="email" placeholder="learner@example.com" className="min-w-0 flex-1 rounded-lg border px-3 py-2"/><button className="rounded-lg bg-blue-700 px-3 py-2 text-sm font-semibold text-white">Add</button><button type="button" onClick={() => void invite()} disabled={!email} className="rounded-lg border px-3 py-2 text-sm font-semibold disabled:opacity-50">Invite link</button></form>{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}{notice ? <p className="mt-3 break-all text-sm text-green-700">{notice}</p> : null}{members.length ? <ul className="mt-4 space-y-2">{members.map((member) => <li key={member.id}>{member.name ?? member.email} <span className="text-sm text-slate-500">{member.email} · {member.status}</span></li>)}</ul> : <p className="mt-3 text-sm text-slate-600">No learners have been added.</p>}</article>;
}
